language: dart
dart:
  # Pin to dev.16 to overcome dartbug.com/31940
  - dev
sudo: false
before_script:
  - ./travis/setup.sh
script:
  - ./travis/format.sh
  - ./travis/build.sh
  - ./travis/test.sh

# We don't build the engine or run the tests for the engine on Travis
# See testing/run_tests.sh if that's what you're looking for though.
